LMB-391: Change rangorde up and down of mandataris in orgaan
lblod/frontend-lokaal-mandatenbeheer pull request #195
Opened 2024-04-30 14:13 UTC by JonasVanHoof

## Description

We want to change the rangorde of a mandataris in orgaan to be moved nup or down in the table. WIP

## How to test

Check the rangorde of the mandaten

2024-05-03 06:30 UTC, Rahien requested changes
need to be able to enter other things than numbers.

2024-05-03 15:27 UTC, ruben-bottu commented
Functionality wise looks good

2024-05-03 15:38 UTC, ruben-bottu commented on app/components/verkiezingen/rangorde-input.js
> +        foundNumber = rangordeStringMapping[key];
Maybe the loop should be ended early if a match is found?

2024-05-03 15:40 UTC, ruben-bottu approved these changes
Looks good

2024-05-06 05:33 UTC, Rahien approved these changes

2024-05-06 05:42 UTC, merged