Lmb 812 hide iv for districts
lblod/frontend-lokaal-mandatenbeheer pull request #366
Opened 2024-10-11 12:03 UTC by JonasVanHoof

## Description

Districts should never see the legislatuur module., they prepare it in the normal interface.

## How to test

1. does not see the menu item (main and compact menu)
2. on mandataris search page the period is not disabled
3. on organen route the `beheer fracties` are enabled
4. the mandatarissen of 2025 - heden can be edited

When in another bestuurseenheid than district the legislatuur should work as before

2024-10-11 12:13 UTC, Rahien requested changes

2024-10-11 12:13 UTC, Rahien commented on app/controllers/mandatarissen/persoon/mandataris.js
> +      return this.model.isDistrictEenheid ? false : true;
why not add this into the if then?

2024-10-11 12:13 UTC, Rahien commented on app/routes/mandatarissen/persoon/mandataris.js
> +      isDistrictEenheid: isDistrict,
we can just make this a property of the session then maybe?

2024-10-11 12:13 UTC, Rahien commented on app/routes/mandatarissen/persoon/mandataris.js
> +      isDistrictEenheid: isDistrict,
same for other cases of this pattern

2024-10-11 12:13 UTC, Rahien commented on app/services/current-session.js
> +    const classificatie = await this.group?.classificatie;
if we fetch this during load, this can be just a getter

2024-10-16 05:45 UTC, Rahien commented
I'm adopting this pr while Jonas is away :)

2024-10-18 07:00 UTC, JonasVanHoof reviewed
Looks good visibility wise But i cannot seem to  open up the beheer fracties button? It works on master, DEV and test but not in this PR :/

To go to the fracties we add the hash bestuursperiode id and this one looks ok so not sure what was changed here, any idea?

2024-10-18 07:00 UTC, JonasVanHoof commented on app/services/current-session.js
> +      this.isDistrict = await this.isDistrictBestuurseenheid();
This is indeed a better approach 💪🏻

2024-10-18 07:05 UTC, JonasVanHoof commented
> Looks good visibility wise But i cannot seem to open up the beheer fracties button? It works on master, DEV and test but not in this PR :/
> 
> To go to the fracties we add the hash bestuursperiode id and this one looks ok so not sure what was changed here, any idea?

This is because we do not have any fracties set for the period, maybe?

2024-10-18 07:45 UTC, bfidlers commented
> > Looks good visibility wise But i cannot seem to open up the beheer fracties button? It works on master, DEV and test but not in this PR :/
> > To go to the fracties we add the hash bestuursperiode id and this one looks ok so not sure what was changed here, any idea?
> 
> This is because we do not have any fracties set for the period, maybe?

No that should not matter, I think it is because in the fractie page we don't allow selecting the bestuursperiod of a bestuursperiod with a installatievergadering that is not behandeld. I think we should remove the installatievergadering for bestuurseenheden that do not need one, with a migration.

2024-10-18 08:39 UTC, Rahien approved these changes
approved after review by jonas (who couldn't approve himself as he started the pr originally)

2024-10-18 08:39 UTC, merged