Lmb 599  | Automatic fillin of search form person info
lblod/frontend-lokaal-mandatenbeheer pull request #379
Opened 2024-10-18 15:40 UTC by JonasVanHoof

## Description

Provide a detailed explanation of the changes you have made. Include the reasons behind these changes and any relevant context.

## How to test

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Links to other PR's

- https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/180

2024-10-21 09:06 UTC, Rahien requested changes

2024-10-21 09:06 UTC, Rahien commented on app/components/rdf-input-fields/rijksregister-input.js
> +      this.removeEmptyBlankNodeFromPrefilledData();
i think that if you create a true uri + type + uuid you won't need this :)

2024-10-21 09:06 UTC, Rahien commented on app/utils/constants.js
> +  persoon: new Namespace('http://data.vlaanderen.be/ns/mandaat#')(
why change this? i don't see the value in first wrapping it to then unwrap it again in the isPredicateInObserverChange.
I'm ok with it though, but i wouldn't have done this. If we can use simple strings we should use simple strings imo

2024-10-21 09:57 UTC, JonasVanHoof commented
More issues from RC ⚠️

1) i entered a rrn and then switched to one without a date (the 00000 one), i couldn't edit the date anymore
2) i entered the fake rrn 06.02.02-000.80 and it assumes my person was born in 1906, i would assume 2006 and i would allow users to modify if we guessed wrong (unlikely)

ofc for endings like 87, still guess dates in the past, not in the future 🙂

2024-10-22 10:00 UTC, JonasVanHoof commented on tests/unit/utils/rijksregisternummer-test.js
> +);
This test will fail but that is ok :)

This is fixed in https://github.com/lblod/frontend-lokaal-mandatenbeheer/pull/385

2024-10-24 11:14 UTC, Rahien approved these changes

2024-10-24 11:16 UTC, merged