add field basic input wrapper component and example
lblod/frontend-lokaal-mandatenbeheer pull request #449
Opened 2024-12-17 12:49 UTC by Rahien

## Description

Allow adding and removing fields to forms (if the form is wrapped in an EditableForm component and the feature flag is on. On by default in development mode).

![image](https://github.com/user-attachments/assets/6d8411b8-ae1b-47d5-9c73-4fa73493d1ae)

![image](https://github.com/user-attachments/assets/ee76c418-31cf-4f9b-b903-237b245b7307)

## How to test

Currently, the only field where this is active is the extra info for a mandataris. So go to a schepen and test it out there. Try adding, refreshing, removing fields
## Links to other PR's

- https://github.com/lblod/form-content-service/pull/63
- https://github.com/lblod/app-lokaal-mandatenbeheer/pull/334

2025-01-06 12:33 UTC, JonasVanHoof commented on app/components/editable-form.js
> +    return this.features.isEnabled('editable-forms');
We could add a features tab in the admin panel to enable or disable these per bestuurseenheid BUT this is not necessary atm ;p

2025-01-06 12:33 UTC, JonasVanHoof commented on app/components/generate-custom-field-button.hbs
> +            @tooltipText="Vul alle informatie in om het veld op te slaan."
optional: "Nog niet al de velden zijn correct ingevuld"

2025-01-06 12:33 UTC, JonasVanHoof commented on app/components/generate-custom-field-button.hbs
> +              Creëer veld
All creating modals use `Voeg toe` in the button and the save button is "Bewaar" (tested this with new mandataris and new orgaan)
![image](https://github.com/user-attachments/assets/450b0469-0701-4328-b95b-ec5e7e564921)

2025-01-06 12:33 UTC, JonasVanHoof commented on app/components/generate-custom-field-button.js
> +    const body = await result.json();
Does it error when there is no result? Just thinking at "Cannot  find method on undefined" or something like that

2025-01-06 12:33 UTC, JonasVanHoof commented on config/environment.js
> +  ENV.features['editable-forms'] = false;
Why enabling and disabling it here and not as the forms feature flag?
```js
    features: {
      'show-forms-module': false,
    },
   ```

2025-01-06 12:33 UTC, JonasVanHoof commented on tests/integration/components/editable-form-test.js
> +import { module, test } from 'qunit';
Do we need to keep these test files?

2025-01-06 12:36 UTC, JonasVanHoof commented on app/components/generate-custom-field-button.js
> +    const body = await result.json();
I didn't checkout the form content service and indeed this is something to handle in the frontend. Also for the other fetches*
![image](https://github.com/user-attachments/assets/f95db2a2-7144-4137-bfae-e29d6d82829e)

2025-01-06 12:47 UTC, JonasVanHoof requested changes
Works good only the remove can be done before saving it

2025-01-06 12:47 UTC, JonasVanHoof commented on app/components/rdf-input-fields/custom-field-wrapper.hbs
> +      Remove
remove or verwijder?

2025-01-06 12:47 UTC, JonasVanHoof commented on app/components/rdf-input-fields/custom-field-wrapper.js
> +    await fetch(`/form-content/fields`, {
It does not wait for the "save" button to remove it?

When i add a field save it, than edit the field remove it and press cancel the field is gone

2025-01-07 15:02 UTC, Rahien commented on config/environment.js
> +  ENV.features['editable-forms'] = false;
so we group everything per environment

2025-01-08 09:36 UTC, JonasVanHoof commented on app/components/rdf-input-fields/custom-field-wrapper.js
> +    await fetch(`/form-content/fields`, {
perfect!

2025-01-08 10:03 UTC, JonasVanHoof reviewed
Two silly additions for the eyes 👀

2025-01-08 10:03 UTC, JonasVanHoof commented on app/components/generate-custom-field-button.hbs
> +              @loading={{this.loading}}
```suggestion
    @loading={{this.loading}}
    @loadingMessage="Bewaren"
```

2025-01-08 10:03 UTC, JonasVanHoof commented on app/components/rdf-input-fields/custom-field-wrapper.hbs
> +      @loading={{this.removing}}
Maybe add a loading message to the button as now it says "Aan het laden"

```suggestion
      @loading={{this.removing}}
      @loadingMessage="Verwijderen"
```

2025-01-08 10:09 UTC, JonasVanHoof commented
I can't seem to find a comment about that the extra info of the custom field is not being visible in the mandataris-extra-info-card.

Maybe this is something for another ticket

2025-01-13 07:25 UTC, JonasVanHoof approved these changes

2025-01-27 13:36 UTC, merged