Lmb 414 | split group mandates in person table
lblod/frontend-lokaal-mandatenbeheer pull request #451
Opened 2024-12-20 11:03 UTC by JonasVanHoof

## Description

We do not want to show the mandates of a person as a comma separated link string. Make it possible to show a dropdown of the rows for the mandaat with the orgaan.

## How to test

Go to mandatarissen module and click open a persoon. The mandaat and orgaan should be clickable and bring you to the correct place.

2025-01-08 08:25 UTC, JonasVanHoof commented on app/components/mandatarissen/persoon-table-row.js
> +  async getSubRowData() {
Not yet convinced to do this in the route

2025-01-08 08:25 UTC, JonasVanHoof commented on app/components/mandatarissen/persoon-table-row.js
> +  @service store;
remove this, unused

2025-01-08 08:25 UTC, JonasVanHoof commented on app/components/mandatarissen/persoon-table-row.hbs
> +    <Mandaat::FoldedFracties
TODO: Do this inline

2025-01-08 08:52 UTC, JonasVanHoof commented on app/components/mandatarissen/persoon-table-row.hbs
> +    <Mandaat::FoldedFracties
To much logic in the component, added an arugment for the component to use the provided mandatarissen

2025-01-08 08:54 UTC, JonasVanHoof commented on app/components/mandatarissen/persoon-table-row.js
> +  async getSubRowData() {
Reason: this component should display subrows, the data structure and template are only used here. If we move this data structure to the route all other components do not have any connecting with it.

2025-01-10 08:09 UTC, Rahien requested changes

2025-01-10 08:09 UTC, Rahien commented on app/components/mandatarissen/persoon-table-row.hbs
> +    <span style={{if (eq this.subRows.length 1) "visibility: hidden" ""}}>
this is not enough. you need a getter to check if it has either more than 1 subrow OR if the only subrow is a mandataris in eigen orgaan

2025-01-10 08:32 UTC, Rahien commented on app/components/mandatarissen/bestuursorganen-as-links.hbs
> +<div {{did-insert (perform this.setup)}}>
i don't like it but i tried to get rid of it and it's not straight forward

2025-01-10 08:40 UTC, Rahien commented on app/components/mandatarissen/persoon-table-row.js
> +  async getSubRowData() {
BUT fetching data in ember should be the responsibility of the routes (except for certain edge cases where that's not possible). In this case that's very possible AND it makes it so that we don't have to do a did-insert which we should avoid

2025-01-10 08:43 UTC, Rahien commented on app/components/mandatarissen/persoon-table.js
> +  mandatarissenFor(persoon) {
should be done in the route. This is a hack, not ember

2025-01-10 10:14 UTC, JonasVanHoof commented on app/components/mandatarissen/persoon-table-row.js
> +  async getSubRowData() {
Moved it

2025-01-10 10:14 UTC, JonasVanHoof commented on app/components/mandatarissen/persoon-table.js
> +  mandatarissenFor(persoon) {
Removed file

2025-01-10 10:15 UTC, JonasVanHoof commented on app/components/mandatarissen/persoon-table-row.hbs
> +    <span style={{if (eq this.subRows.length 1) "visibility: hidden" ""}}>
removed did-insert + changed subRows.length to mandatarissen.length (see new logic)

2025-01-10 10:51 UTC, Rahien approved these changes
i think we are still doing too many calls, but we've always done that and fixing it now would be premature optimization.

2025-01-10 10:54 UTC, merged