Allow modifying bestuursorganen (niet decretaal), view only on decretaal
lblod/frontend-lokaal-mandatenbeheer pull request #60
Opened 2024-02-19 10:18 UTC by ruben-bottu

2024-02-19 10:45 UTC, bfidlers approved these changes
Looks good and can certainly be merged into the Karel/lmb-116 branch, but probably best to rebase this first in the current structure of the bestuursorganen subpage before merging to master.

2024-02-19 10:45 UTC, bfidlers commented on tests/unit/controllers/mandatenbeheer/bestuursorganen/edit-test.js
I'm not really a fan of including empty tests ...

2024-02-19 10:45 UTC, bfidlers commented on app/templates/mandatenbeheer/fracties/edit.hbs
Not sure why this file is edited, doesn't really seem to have anything to do with this PR?

2024-02-19 10:45 UTC, bfidlers commented on app/templates/mandatenbeheer/bestuursorganen/edit.hbs
> +    <AuHeading @skin="2">Bewerk fractie</AuHeading>
Headers are wrong here.

2024-02-20 09:04 UTC, bfidlers requested changes
Needs to be re-reviewed

2024-02-20 11:01 UTC, Rahien requested changes
could we get a screenshot of the end result before approving?

2024-02-20 11:09 UTC, ruben-bottu commented on app/models/bestuursorgaan.js
> +      : await this.classificatie.get('uri');
What about bestuursorgaan? I guess it doens't have to be awaited anymore

2024-02-20 12:03 UTC, Rahien commented on app/models/bestuursorgaan.js
> +      : await this.classificatie.get('uri');
it already is on line 55

2024-02-20 13:08 UTC, Rahien approved these changes

2024-02-20 13:22 UTC, merged