Layout bestuursorgaan pagina
lblod/frontend-lokaal-mandatenbeheer pull request #85
Opened 2024-02-27 17:22 UTC by ruben-bottu

![image](https://github.com/lblod/frontend-lokaal-mandatenbeheer/assets/55446974/e05da37f-1c5b-427f-b055-4233881ee06f)

2024-02-27 17:23 UTC, ruben-bottu commented
Sadly mandaten overview still breaks if you switch to it from details and mandatarissen tabs

2024-02-28 08:07 UTC, Rahien requested changes

2024-02-28 08:07 UTC, Rahien commented on app/components/mandatenbeheer/bestuursorgaan-mandaten.hbs
> +  {{did-update this.initialize.perform @mandaten}}
```suggestion
  {{did-update this.initialize.perform @mandaten}}
  {{did-insert this.initialize.perform}}
```

2024-02-28 08:07 UTC, Rahien commented on app/components/mandatenbeheer/bestuursorgaan-mandaten.hbs
> +  {{did-update this.initialize.perform @mandaten}}
you need both or on first render the orderedMandaten is not computed

2024-02-28 08:07 UTC, Rahien commented on app/components/mandatenbeheer/bestuursorgaan-mandaten.hbs
> +  {{did-update this.initialize.perform @mandaten}}
like we said, it would be much more clean to do this in the route but i think you created a story for that?

2024-02-28 09:05 UTC, Rahien approved these changes

2024-02-28 10:36 UTC, merged